package parker

import meshruntimepkg "github.com/parkerpoker/parkerd/internal/meshruntime"

type NativePeerAddress = meshruntimepkg.NativePeerAddress
type NativeMeshPeerState = meshruntimepkg.NativeMeshPeerState
type NativeTableSummary = meshruntimepkg.NativeTableSummary
type NativeMeshRuntimeState = meshruntimepkg.NativeMeshRuntimeState
type NativeMeshTableConfig = meshruntimepkg.NativeMeshTableConfig
type NativeSeatedPlayer = meshruntimepkg.NativeSeatedPlayer
type NativeDealerCommitment = meshruntimepkg.NativeDealerCommitment
type NativePublicTableState = meshruntimepkg.NativePublicTableState
type NativeTableSnapshotSignature = meshruntimepkg.NativeTableSnapshotSignature
type NativeCooperativeTableSnapshot = meshruntimepkg.NativeCooperativeTableSnapshot
type NativeAdvertisement = meshruntimepkg.NativeAdvertisement
type NativePublicTableView = meshruntimepkg.NativePublicTableView
type NativeTableLocalView = meshruntimepkg.NativeTableLocalView
type NativeMeshTableView = meshruntimepkg.NativeMeshTableView
type NativeSignedTableEvent = meshruntimepkg.NativeSignedTableEvent
type NativeTableFundsOperation = meshruntimepkg.NativeTableFundsOperation
type NativeTableFundsEntry = meshruntimepkg.NativeTableFundsEntry
type NativeTableFundsState = meshruntimepkg.NativeTableFundsState
